### ISSUE TITLE
执行./BookStack install时载入sego词典失败

### ISSUE THREAD

**Issue by BoomTian** [TruthHun/BookStack#131]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 BookStack?
2.8

2. 你当前使用的是什么操作系统?
ubuntun

3. 你是如何操作的？
按文档操作

4. 你期望得到什么结果?
成功运行

5. 当前遇到的是什么结果?
执行./BookStack install时拒绝
2021/03/23 23:40:27 载入sego词典 /root/dictionary/dictionary.txt
panic: Error 1045: Access denied for user ''@'localhost' (using password: NO)

goroutine 1 [running]:
github.com/TruthHun/BookStack/commands.RegisterDataBase()
	D:/workspace/golang/src/github.com/TruthHun/BookStack/commands/command.go:49 +0x651
github.com/TruthHun/BookStack/commands.ResolveCommand(0xc00000c080, 0x0, 0x0)
	D:/workspace/golang/src/github.com/TruthHun/BookStack/commands/command.go:273 +0x7ae
github.com/TruthHun/BookStack/commands.RegisterCommand()
	D:/workspace/golang/src/github.com/TruthHun/BookStack/commands/command.go:141 +0x17e
main.main()
	D:/workspace/golang/src/github.com/TruthHun/BookStack/main.go:26 +0xd8

**Comment by BoomTian** [comment]
已解决，但是http server Running on http://:8181跑起来后进不去页面，有大佬帮帮忙吗

**Comment by BoomTian** [comment]
是进http://demo.bookstack.cn/这个页面吗
