### ISSUE TITLE
chrome、puppeteer 安装不成功

### ISSUE THREAD

**Issue by diyes** [TruthHun/BookStack#151]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 BookStack?
[v2.10]

2. 你当前使用的是什么操作系统?
Ubuntu 18.04

3. 你是如何操作的？
安装chrome、puppeteer  出错，后跳过该步骤直接下一步安装bookstack，可以进系统，后台出现错误，
`<html>
<body>

chrome | 未安装 | chrome浏览器，即谷歌浏览器，或者chromium-browser，用于渲染markdown内容为HTML。 | fork/exec /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome: no such file or directory
-- | -- | -- | --
puppeteer | 未安装 | puppeteer, node.js的模块，用于将markdown渲染为HTML以及生成电子书封面。 安装教程 | exit status 1 module.js:549 throw err; ^ Error: Cannot find module 'puppeteer' at Function.Module._resolveFilename (module.js:547:15) at Function.Module._load (module.js:474:25) at Module.require (module.js:596:17) at require (internal/module.js:11:18) at Object.<anonymous> (/www/wwwroot/172.16.11.85/test.js:2:19) at Module._compile (module.js:652:30) at Object.Module._extensions..js (module.js:663:10) at Module.load (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load (module.js:497:3)

</body>
</html>`

4. 你期望得到什么结果?

安装成功
5. 当前遇到的是什么结果?
![](https://i.bmp.ovh/imgs/2022/03/94e407f40bf557e2.png)

**Comment by zining3235** [comment]
# 谷歌浏览器，用于发布内容的时候渲染未被渲染的markdown。建议安装最新版的Chrome浏览器，并把Chrome浏览器加入系统环境变量。
# 使用Chrome的headless去处理。之前考虑使用phantomjs的，但是phantomjs有些小问题，不如Chrome强大。
chrome=chromium-browser
chrome=/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome
chrome=/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome
chrome=chromium-browser
# 如果使用 puppeteer，则忽略chrome
puppeteer = false

**Comment by Yuelioi** [comment]
chrome安装步骤那里 不是有个让你打印百度页面么 不成功说明你chrome不行 重安chrome
