### ISSUE TITLE
安装数据库时报错

### ISSUE THREAD

**Issue by oalinux** [TruthHun/BookStack#17]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 BookStack?
BookStack.V1.2_linux_amd64.zip

2. 你当前使用的是什么操作系统?
ubuntu 16.04

3. 你是如何操作的？
./BookStack install

4. 你期望得到什么结果?
安装成功

5. 当前遇到的是什么结果?

public_html# ./BookStack install
2018/04/22 15:46:37 载入sego词典 /mnt/wwwroot/doc.bookgod.com/public_html/dictionary/dictionary.txt
Initializing...
table `md_members` already exists, skip
table `md_books` already exists, skip
table `md_relationship` already exists, skip
table `md_options` already exists, skip
table `md_documents` already exists, skip
table `md_attachment` already exists, skip
table `md_logs` already exists, skip
table `md_member_token` already exists, skip
table `md_document_history` already exists, skip
table `md_migrations` already exists, skip
table `md_label` already exists, skip
table `md_seo` already exists, skip
table `md_star` already exists, skip
table `md_score` already exists, skip
table `md_comments` already exists, skip
table `md_gitee` already exists, skip
table `md_github` already exists, skip
table `md_qq` already exists, skip
table `md_document_store` already exists, skip
table `md_category` already exists, skip
table `md_book_category` already exists, skip
table `md_fans` already exists, skip
table `md_friend_link` already exists, skip
[ORM]2018/04/22 15:46:38  -[Queries/default] - [  OK / db.QueryRow /     0.3ms] - [SELECT COUNT(*) FROM `md_options` T0 WHERE T0.`option_name` = ? ] - `ENABLED_REGISTER`
[ORM]2018/04/22 15:46:38  -[Queries/default] - [FAIL /     db.Exec /     0.2ms] - [INSERT INTO `md_options` (`option_title`, `option_name`, `option_value`, `remark`) VALUES (?, ?, ?, ?)] - `是否启用注册`, `ENABLED_REGISTER`, `true`, `` - Error 1366: Incorrect string value: '\xE6\x98\xAF\xE5\x90\xA6...' for column 'option_title' at row 1
panic: Error 1366: Incorrect string value: '\xE6\x98\xAF\xE5\x90\xA6...' for column 'option_title' at row 1

goroutine 1 [running]:
github.com/TruthHun/BookStack/commands.initialization()
	/Users/TruthHun/goworkspace/src/github.com/TruthHun/BookStack/commands/install.go:47 +0x8bb
github.com/TruthHun/BookStack/commands.Install()
	/Users/TruthHun/goworkspace/src/github.com/TruthHun/BookStack/commands/install.go:23 +0x9f
github.com/TruthHun/BookStack/commands.RegisterCommand()
	/Users/TruthHun/goworkspace/src/github.com/TruthHun/BookStack/commands/command.go:126 +0x1a4
main.main()
	/Users/TruthHun/goworkspace/src/github.com/TruthHun/BookStack/main.go:25 +0x100

**Comment by tianxdy** [comment]
可以问下您，./BookStack 怎么出来的哦。我这没有这个可执行文件

**Comment by 52fhy** [comment]
请检查数据库字符集是否是utf8
