### ISSUE TITLE
install时数据库出错 panic: Member.Add => 密码不能为空且必须在6-50个字符之间

### ISSUE THREAD

**Issue by CN-P5** [TruthHun/BookStack#57]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 BookStack?
2.0
2. 你当前使用的是什么操作系统?
debian windows10 都可以重现
3. 你是如何操作的？
./BookStack install
4. 你期望得到什么结果?
安装成功的提示
5. 当前遇到的是什么结果?
安装不成功，部分日志：
‘’‘
[ORM]2019/08/15 03:48:53  -[Queries/default] - [  OK /    db.Query /     0.4ms] - [SELECT T0.`member_id`, T0.`account`, T0.`nickname`, T0.`password`, T0.`auth_method`, T0.`description`, T0.`email`, T0.`phone`, T0.`avatar`, T0.`role`, T0.`status`, T0.`create_time`, T0.`create_at`, T0.`last_login_time`, T0.`wxpay`, T0.`alipay` FROM `md_members` T0 WHERE T0.`account` = ? ORDER BY T0.`member_id` DESC LIMIT 1] - `admin`
panic: Member.Add => 密码不能为空且必须在6-50个字符之间

goroutine 1 [running]:
github.com/TruthHun/BookStack/commands.initialization()
	D:/workspace/golang/src/github.com/TruthHun/BookStack/commands/install.go:63 +0x792
github.com/TruthHun/BookStack/commands.Install()
	D:/workspace/golang/src/github.com/TruthHun/BookStack/commands/install.go:23 +0xae
github.com/TruthHun/BookStack/commands.RegisterCommand()
	D:/workspace/golang/src/github.com/TruthHun/BookStack/commands/command.go:124 +0x198
main.main()
	D:/workspace/golang/src/github.com/TruthHun/BookStack/main.go:24 +0xe5

’‘’

**Comment by TruthHun** [comment]
今天早上重新编译了一个版本，把管理员默认账号密码调整为：
```
admin
admin888
```
重新下载新版本，再次执行安装。
