### ISSUE TITLE
Windows如何直接部署到localhost? 无需oauth和oss功能.

### ISSUE THREAD

**Issue by yfh19961130** [TruthHun/BookStack#78]
1. 你当前使用的是哪个版本的 BookStack?
BookStack.V2.3

2. 你当前使用的是什么操作系统?
Windows_adm64

3. 你是如何操作的？
- 修改app.conf, 修改如下:
static_domain= localhost
db_host=localhost
db_port=3307
db_username=bookstack
db_password=此处省略
- cmd运行BookStack.exe install
- 双击BookStack.exe
4. 你期望得到什么结果?
Windows直接部署到localhost, 无需oauth和oss功能.

5. 当前遇到的是什么结果?

- cmd显示

Service:  BookStack
Version:  v2.3
BuildAt:  2019-12-02T21:56:45+0800
GitHash:  7e7438c305b8b4401bc7ad933a32fd7528db5340
2019/12/15 19:18:46 载入sego词典 D:\Program_Files\BookStack.V2.3_Win64/dictionary/dictionary.txt
[ORM]2019/12/15 19:18:46  -[Queries/default] - [FAIL /    db.Query /     1.0ms] - [SELECT T0.`id`, T0.`title`, T0.`identify`, T0.`is_mobile` FROM `md_ads_position` T0 ] - Error 1146: Table 'bookstack.md_ads_position' doesn't exist
[ORM]2019/12/15 19:18:46  -[Queries/default] - [FAIL /    db.Query /     0.0ms] - [SELECT T0.`id`, T0.`pid`, T0.`title`, T0.`code`, T0.`start`, T0.`end`, T0.`status` FROM `md_ads_cont` T0 WHERE T0.`status` = ? AND T0.`start` < ? AND T0.`end` > ? ] - `1`, `1576408726`, `1576408726` - Error 1146: Table 'bookstack.md_ads_cont' doesn't exist
2019/12/15 19:18:46.956 [I] [ads.go:222]   =============== update ads cache ===============
2019/12/15 19:18:47.661 [I] [asm_amd64.s:1357]  http server Running on http://:8181
2019/12/15 19:18:52 sego词典载入完毕
- 浏览器访问localhost:8081 没网页

**Comment by TruthHun** [comment]
再执行一次`BookStack.exe install`

同时注意报错日志

程序需要加入到系统守护进程，`pm2`可以了解下

**Comment by hugetiny** [comment]
V2.5报这个错
BookStack.exe install
```
panic: open C:\Users\huget\documents\bookstack25\conf\oss.conf: The system cannot find the file specified.                                                                                                                                                                                                                                                                                          goroutine 1 [running]:                                                                                                                                                                            github.com/astaxie/beego.init.2()                                                                                                                                                                         /Users/TruthHun/goworkspace/pkg/mod/github.com/astaxie/beego@v1.12.0/config.go:157 +0x475 
```

**Comment by hugetiny** [comment]
2.5遇到同样情况
