### ISSUE TITLE
2.6版本，在centos下安装，执行到./BookStack install报错路径包含window路径

### ISSUE THREAD

**Issue by ldbinac** [TruthHun/BookStack#88]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 BookStack?
编译后的2.6版本（ BookStack.V2.6_Linux_amd64.zip）

2. 你当前使用的是什么操作系统?
centOS 7

3. 你是如何操作的？
参考Ubuntu的安装模式，执行安装，进行到./BookStack install时报错

4. 你期望得到什么结果?
正常安装

5. 当前遇到的是什么结果?
```
[root@CentOS8x64 bookstack]# ./BookStack install
2020/03/20 13:35:05 载入sego词典 /data/bookstack/dictionary/dictionary.txt
panic: dial tcp [::1]:3306: connect: connection refused

goroutine 1 [running]:
github.com/TruthHun/BookStack/commands.RegisterDataBase()
	D:/workspace/golang/src/github.com/TruthHun/BookStack/commands/command.go:49 +0x651
github.com/TruthHun/BookStack/commands.ResolveCommand(0xc0000a2020, 0x0, 0x0)
	D:/workspace/golang/src/github.com/TruthHun/BookStack/commands/command.go:272 +0x7ae
github.com/TruthHun/BookStack/commands.RegisterCommand()
	D:/workspace/golang/src/github.com/TruthHun/BookStack/commands/command.go:140 +0x17d
main.main()
	D:/workspace/golang/src/github.com/TruthHun/BookStack/main.go:26 +0xe5
```

为啥在Linux下安装时竟然报Windows的错误呢？
请问该如何解决？

**Comment by ldbinac** [comment]
把源码下来之后，跟进看了一下对应的行数的问题，原来是由于 MySQL数据库连不上导致的，进而去跟进服务器的MySQL的情况，发现数据库由于关机未能启动，所以导致问题。

只是目前这个报错的信息不是特别明显。至于报错当中的window路径的问题，猜测可能是go语言自己的报错就是这个样子的吧，没有接触过go。
