### ISSUE TITLE
centos安装提示出错

### ISSUE THREAD

**Issue by ricardokehua** [TruthHun/BookStack#94]
1. 你当前使用的是哪个版本的 BookStack?
V2.6

2. 你当前使用的是什么操作系统?
centos7.6

3. 你是如何操作的？
按照安装步骤进行操作

4. 你期望得到什么结果?
安装成功

5. 当前遇到的是什么结果?
2020/03/31 12:59:30 载入sego词典 /root/dictionary/dictionary.txt
panic: dial tcp :3306: connect: connection refused

goroutine 1 [running]:
github.com/TruthHun/BookStack/commands.RegisterDataBase()
        D:/workspace/golang/src/github.com/TruthHun/BookStack/commands/command.go:49 +0x651
github.com/TruthHun/BookStack/commands.ResolveCommand(0xc00000c080, 0x0, 0x0)
        D:/workspace/golang/src/github.com/TruthHun/BookStack/commands/command.go:272 +0x7ae
github.com/TruthHun/BookStack/commands.RegisterCommand()
        D:/workspace/golang/src/github.com/TruthHun/BookStack/commands/command.go:140 +0x17d
main.main()
        D:/workspace/golang/src/github.com/TruthHun/BookStack/main.go:26 +0xe5

**Comment by ldbinac** [comment]
这个提示是数据库连不到的意思，你测试一下在你的centos服务器上数据库是否可以正常连上
